/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuestionario;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Preguntas extends javax.swing.JFrame {
    
    
    String color="",cadena1="",cadena2="",cadena3="";
    String cade1="",cade2="";
    
    public void validarCheck(){
        
        if(CheckBox1.isSelected()){
        cadena1="Rock";
        }
        if(CheckBox2.isSelected()){
        cadena2=" Blues";
        }
        if(CheckBox3.isSelected()){
        cadena3=" Country";
        }
        
        
        cade1=cadena1.concat(cadena2);
        cade2=cade1.concat(cadena3);
        
        TextField3.setText(cade2);
    
    }
    


    /**
     * Creates new form Preguntas
     */
    public Preguntas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Color = new javax.swing.ButtonGroup();
        SiNo = new javax.swing.ButtonGroup();
        TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RadioButton1 = new javax.swing.JRadioButton();
        RadioButton2 = new javax.swing.JRadioButton();
        RadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        CheckBox1 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        Button1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextField3 = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        simon = new javax.swing.JRadioButton();
        nel = new javax.swing.JRadioButton();
        T4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldActionPerformed(evt);
            }
        });
        TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldKeyTyped(evt);
            }
        });

        jLabel1.setText("1.-¿Prefieres Frio o  Calor?");

        jLabel2.setText("2.-¿Cual es tu color favorito?");

        Color.add(RadioButton1);
        RadioButton1.setText("Rojo");
        RadioButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RadioButton1MouseMoved(evt);
            }
        });
        RadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioButton1MouseClicked(evt);
            }
        });
        RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton1ActionPerformed(evt);
            }
        });

        Color.add(RadioButton2);
        RadioButton2.setText("Negro");
        RadioButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RadioButton2MouseMoved(evt);
            }
        });
        RadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioButton2MouseClicked(evt);
            }
        });

        Color.add(RadioButton3);
        RadioButton3.setText("Azul");
        RadioButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RadioButton3MouseMoved(evt);
            }
        });
        RadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioButton3MouseClicked(evt);
            }
        });

        jLabel3.setText("3.-¿Qué musica te gusta?");

        CheckBox1.setText("Rock");
        CheckBox1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CheckBox1MouseMoved(evt);
            }
        });
        CheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckBox1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CheckBox1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CheckBox1MouseReleased(evt);
            }
        });
        CheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox1ActionPerformed(evt);
            }
        });

        CheckBox2.setText("Blues");
        CheckBox2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CheckBox2MouseMoved(evt);
            }
        });
        CheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckBox2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CheckBox2MousePressed(evt);
            }
        });

        CheckBox3.setText("Country");
        CheckBox3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CheckBox3MouseMoved(evt);
            }
        });
        CheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckBox3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CheckBox3MousePressed(evt);
            }
        });

        Button1.setText("Terminar");
        Button1.setEnabled(false);
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
        });
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Respuestas");

        TextField1.setEditable(false);

        jLabel5.setText("1.-");

        jLabel6.setText("2.-");

        TextField2.setEditable(false);

        jLabel7.setText("3.-");

        TextField3.setEditable(false);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel8.setText("4.-¿Te gusta el pan?");

        SiNo.add(simon);
        simon.setText("Si");
        simon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simonMouseClicked(evt);
            }
        });

        SiNo.add(nel);
        nel.setText("No");
        nel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nelMouseClicked(evt);
            }
        });

        T4.setEditable(false);

        jLabel9.setText("4.-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button1)
                .addGap(89, 89, 89)
                .addComponent(Salir))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBox3)
                            .addComponent(CheckBox2)
                            .addComponent(CheckBox1)
                            .addComponent(RadioButton3)
                            .addComponent(RadioButton2)
                            .addComponent(RadioButton1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nel)
                                    .addComponent(simon))
                                .addGap(203, 203, 203))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TextField))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addContainerGap(65, Short.MAX_VALUE))
                                .addComponent(TextField3)
                                .addComponent(TextField2)
                                .addComponent(TextField1))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(TextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1)
                    .addComponent(Salir)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
     
              
        
        
        String dato;
     
     dato=this.TextField.getText();
     
     this.TextField.setText("");
     this.TextField1.setText(dato);
     
     TextField2.setText(color);
          
     validarCheck();
     
     if(simon.isSelected())
     {
     T4.setText("Si");
     }
     else if(nel.isSelected())
     {
     T4.setText("No");
     }
     
      
     
     
     
     
    }//GEN-LAST:event_Button1ActionPerformed

    private void RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton1ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
    
        int op=0;//0 es "no" 1 es "si"
        
        op=JOptionPane.showConfirmDialog(null,"¿Estas Seguro?","¿Estas Seguro?",JOptionPane.YES_NO_OPTION);
        
        if(op!=1)
        {
        System.exit(0); 
        }
    
        
               // TODO add your handling code here:
        
        
    }//GEN-LAST:event_SalirActionPerformed

    private void RadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioButton1MouseClicked
                // color rojo
        //TextField2.setText("Rojo");
        color="Rojo";
        TextField2.setText("");
        
    }//GEN-LAST:event_RadioButton1MouseClicked

    private void RadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioButton2MouseClicked
        // color negro
        //TextField2.setText("Negro");
        color="Negro";
        TextField2.setText("");
    }//GEN-LAST:event_RadioButton2MouseClicked

    private void RadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioButton3MouseClicked
        // color azul
        //TextField2.setText("Azul");
        color="Azul";
        TextField2.setText("");
    }//GEN-LAST:event_RadioButton3MouseClicked

    private void CheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox1ActionPerformed

    private void CheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox1MouseClicked
        // TODO add your handling code here:
            if(CheckBox1.isSelected()){
        Button1.setEnabled(true);
    }
    }//GEN-LAST:event_CheckBox1MouseClicked

    private void CheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox2MouseClicked
        // TODO add your handling code here:
                if(CheckBox2.isSelected()){
        Button1.setEnabled(true);
    }
    }//GEN-LAST:event_CheckBox2MouseClicked

    private void CheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox3MouseClicked
        // TODO add your handling code here:
                if(CheckBox3.isSelected()){
        Button1.setEnabled(true);
    }
    }//GEN-LAST:event_CheckBox3MouseClicked

    private void CheckBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox1MousePressed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_CheckBox1MousePressed

    private void CheckBox2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox2MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_CheckBox2MousePressed

    private void CheckBox3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox3MousePressed
        // TODO add your handling code here:


    }//GEN-LAST:event_CheckBox3MousePressed

    private void TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldKeyTyped
       
        char esta = evt.getKeyChar();//Validacion solo letras
        if(!(esta<33 || esta>64)){
            evt.consume();
        JOptionPane.showMessageDialog(null,"Solo puedes ingresar letras","ERROR",JOptionPane.ERROR_MESSAGE);//Error
        }
 

        
        
    }//GEN-LAST:event_TextFieldKeyTyped

    private void CheckBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox1MouseReleased

    int band=0;
    private void CheckBox1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox1MouseMoved
    if (band==0){
    JOptionPane.showMessageDialog(rootPane,"Puedes seleccionar varios");//Informacion
    band=1;
     }
    
    }//GEN-LAST:event_CheckBox1MouseMoved

    private void CheckBox2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox2MouseMoved
    if (band==0){
    JOptionPane.showMessageDialog(rootPane,"Puedes seleccionar varios");//Informacion
    band=1;
     }
    }//GEN-LAST:event_CheckBox2MouseMoved

    private void CheckBox3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox3MouseMoved
    if (band==0){
    JOptionPane.showMessageDialog(rootPane,"Puedes seleccionar varios");//Informacion
    band=1;
     }
    }//GEN-LAST:event_CheckBox3MouseMoved

    int band2=0;
    private void RadioButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioButton1MouseMoved
    
        if(band2==0){
        JOptionPane.showMessageDialog(null,"Solo puedes seleccionar uno","Advertencia",JOptionPane.WARNING_MESSAGE);//Advertencia
        band2=1;
        }
    }//GEN-LAST:event_RadioButton1MouseMoved

    private void RadioButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioButton2MouseMoved
        if(band2==0){
        JOptionPane.showMessageDialog(null,"Solo puedes seleccionar uno","Advertencia",JOptionPane.WARNING_MESSAGE);//Advertencia
        band2=1;
        }
    }//GEN-LAST:event_RadioButton2MouseMoved

    private void RadioButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioButton3MouseMoved
       if(band2==0){
        JOptionPane.showMessageDialog(null,"Solo puedes seleccionar uno","Advertencia",JOptionPane.WARNING_MESSAGE);//Advertencia
        band2=1;
        }
    }//GEN-LAST:event_RadioButton3MouseMoved

    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Button1MouseClicked

    private void simonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simonMouseClicked
        
        if(simon.isSelected())
        {
        JOptionPane.showInputDialog("¿Por que te gustan?");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_simonMouseClicked

    private void nelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nelMouseClicked
        
        if(nel.isSelected())
        {
        JOptionPane.showInputDialog("¿Por que no te gustan?");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_nelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Button1;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox3;
    public static javax.swing.ButtonGroup Color;
    private javax.swing.JRadioButton RadioButton1;
    private javax.swing.JRadioButton RadioButton2;
    private javax.swing.JRadioButton RadioButton3;
    private javax.swing.JButton Salir;
    public static javax.swing.ButtonGroup SiNo;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField TextField;
    private javax.swing.JTextField TextField1;
    private javax.swing.JTextField TextField2;
    private javax.swing.JTextField TextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton nel;
    private javax.swing.JRadioButton simon;
    // End of variables declaration//GEN-END:variables

    private void strcat(String cadena2, String cadena1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void sageDialog(Object object, String solo_puedes_ingresar_letras, String error, int ERROR_MESSAGE) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
