/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package texto;

import java.awt.Color;
import java.awt.Font;
import java.util.Scanner;

/**
 *
 * @author Usuario
 */
public class TextoProp extends javax.swing.JFrame {

    /**
     * Creates new form TextoProp
     */
    public TextoProp() {
        initComponents();
    }
    private Color color;
    private Font fuente;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T1 = new javax.swing.JLabel();
        T2 = new javax.swing.JLabel();
        T3 = new javax.swing.JLabel();
        Aumentar = new javax.swing.JButton();
        Disminuir = new javax.swing.JButton();
        Color = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Color1 = new javax.swing.JButton();
        Color2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        T1.setText("Ivan Felipe Campos Esparza");

        T2.setText("1631113243");

        T3.setText("Ing.Software");

        Aumentar.setText("Aumentar");
        Aumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarActionPerformed(evt);
            }
        });

        Disminuir.setText("Disminuir");
        Disminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirActionPerformed(evt);
            }
        });

        Color.setText("Rojo");
        Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MS Mincho", 1, 18)); // NOI18N
        jLabel4.setText("Editar Texto en tiempo real");

        Color1.setText("Verde");
        Color1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Color1ActionPerformed(evt);
            }
        });

        Color2.setText("Azul");
        Color2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Color2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Aumentar)
                        .addGap(43, 43, 43)
                        .addComponent(Disminuir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(Color1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Color2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(T3)
                            .addComponent(T2)
                            .addComponent(T1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Color)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addComponent(T1)
                .addGap(18, 18, 18)
                .addComponent(T2)
                .addGap(18, 18, 18)
                .addComponent(T3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(Color)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aumentar)
                    .addComponent(Disminuir)
                    .addComponent(Color1)
                    .addComponent(Color2))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorActionPerformed
    
     color = new Color(255,0,0);
     T1.setForeground(color);
     T2.setForeground(color);
     T3.setForeground(color); 
        

    }//GEN-LAST:event_ColorActionPerformed

    private void AumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarActionPerformed
     fuente = new Font("Arial",Font.BOLD,20);
     T1.setFont(fuente);
     T2.setFont(fuente);
     T3.setFont(fuente);
    }//GEN-LAST:event_AumentarActionPerformed

    private void DisminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirActionPerformed
     fuente = new Font("Arial",Font.BOLD,10);
     T1.setFont(fuente);
     T2.setFont(fuente);
     T3.setFont(fuente);
    }//GEN-LAST:event_DisminuirActionPerformed

    private void Color1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Color1ActionPerformed
     color = new Color(0,255,0);
     T1.setForeground(color);
     T2.setForeground(color);
     T3.setForeground(color); 
    }//GEN-LAST:event_Color1ActionPerformed

    private void Color2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Color2ActionPerformed
     color = new Color(0,0,255);
     T1.setForeground(color);
     T2.setForeground(color);
     T3.setForeground(color); 
    }//GEN-LAST:event_Color2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextoProp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextoProp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextoProp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextoProp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextoProp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aumentar;
    private javax.swing.JButton Color;
    private javax.swing.JButton Color1;
    private javax.swing.JButton Color2;
    private javax.swing.JButton Disminuir;
    private javax.swing.JLabel T1;
    private javax.swing.JLabel T2;
    private javax.swing.JLabel T3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
